packages:
  - "packages/qson-axios"
  - "packages/qson-dev"
  - "packages/qson-express"
  - "packages/qson-js"
  - "packages/qson-react"
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@qson/js@0.2.2'
