name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    accept:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5

            - uses: pnpm/action-setup@v5

            - uses: actions/setup-node@v5
              with:
                    node-version: 24
                    cache: pnpm

            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint
            - run: pnpm run test
              working-directory: packages/qson-js
            - run: pnpm run release --no-tag-check --dry-run
              working-directory: packages/qson-js
            - run: pnpm run test
              working-directory: packages/qson-express
            - run: pnpm run release --no-tag-check --dry-run
              working-directory: packages/qson-express
            - run: pnpm run test
              working-directory: packages/qson-axios
            - run: pnpm run release --no-tag-check --dry-run
              working-directory: packages/qson-axios
